dist: trusty
sudo: required
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - g++-6
            - libboost-all-dev
            - clang-format-6.0
            - libncurses-dev
            - tmux
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - g++-7
            - libboost-all-dev
            - clang-format-6.0
            - libncurses-dev
            - tmux
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - g++-8
            - libboost-all-dev
            - clang-format-6.0
            - libncurses-dev
            - tmux
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
    - eval "${MATRIX_EVAL}"
    - pip install --user tox

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . -- clang-format-run
  - cmake --build . -- perg -j2
  - cmake --build . -- perg-ut-run -j2
  - cmake --build . -- perg-pytest-run
  - cmake --build . -- perg-benchmark-run -j2
